# Generated by Django 5.2.1 on 2025-05-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurship', '0002_remove_customer_email_remove_customer_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='roadmapitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='writtencontent',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurship.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurship.customer')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Entrepreneurship.tag'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurship.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurship.customer')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurship.videocontent')),
            ],
            options={
                'unique_together': {('customer', 'course', 'video')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_completed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurship.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurship.customer')),
                ('last_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Entrepreneurship.videocontent')),
            ],
            options={
                'unique_together': {('customer', 'course')},
            },
        ),
    ]
